/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
export async function seed(knex) {
  // Deletes ALL existing entries
  await knex('findbooks').del()
  await knex('findbooks').insert([
    {
      id: 1,
      attribute: 'Rags to Riches',
      title: 'Great Expectations',
      author: 'Charles Dickens',
      summary: 'Orphan levels up, realizes money cannot buy class.',
    },
    {
      id: 2,
      attribute: 'Sharp Satire',
      title: 'Catch-22',
      author: 'Joseph Heller',
      summary: 'War is crazy, paperwork is crazier.',
    },
    {
      id: 3,
      attribute: 'Sharp Satire',
      title: 'Animal Farm',
      author: 'George Orwell',
      summary: 'Pigs discover communism, other animals not impressed.',
    },
    {
      id: 4,
      attribute: 'Adventure',
      title: 'Jurassic Park',
      author: 'Michael Crichton',
      summary: 'Dinosaur theme park, what could go wrong?',
    },
    {
      id: 5,
      attribute: 'Chaos Ensues',
      title: 'A Confederacy of Dunces',
      author: 'John Kennedy Toole',
      summary: 'Man-child wreaks havoc in New Orleans, calls it philosophy.',
    },
    {
      id: 6,
      attribute: 'Chaos Ensues',
      title: 'Alices Adventures in Wonderland',
      author: 'Lewis Carroll',
      summary: 'Girl follows rabbit, sanity optional.',
    },
    {
      id: 7,
      attribute: 'Real Scary',
      title: 'House of Leaves',
      author: 'Mark Z. Danielewski',
      summary: 'House bigger on inside, sanity smaller on outside.',
    },
    {
      id: 8,
      attribute: 'Real Scary',
      title: 'The Shining',
      author: 'Stephen King',
      summary: 'Family vacation goes wrong.',
    },
    {
      id: 9,
      attribute: 'Endless Family Drama',
      title: 'One Hundred Years of Solitude',
      author: 'Gabriel García Márquez',
      summary: 'Seven generations of mistakes, magic realism cannot fix it.',
    },
    {
      id: 10,
      attribute: 'Endless Family Drama',
      title: 'The God of Small Things',
      author: 'Arundhati Roy',
      summary: 'Twins learn family secrets, wish they had not.',
    },
    {
      id: 11,
      attribute: 'Chaos Ensues',
      title: "The Hitchhiker's Guide to the Galaxy",
      author: 'Douglas Adams',
      summary: 'Earth demolished, man tours universe in bathrobe.',
    },
    {
      id: 12,
      attribute: 'Rags to Riches',
      title: 'Charlie and the Chocolate Factory',
      author: 'Roald Dahl',
      summary:
        'Poor kid wins candy factory, previous owner definitely not sued.',
    },
    {
      id: 13,
      attribute: 'Real Scary',
      title: 'It',
      author: 'Stephen King',
      summary:
        'Killer clown terrorizes town, children fight back with power of friendship.',
    },
    {
      id: 14,
      attribute: 'Adventure',
      title: 'The Hobbit',
      author: 'J.R.R. Tolkien',
      summary: 'Short man takes long walk, finds jewelry.',
    },
    {
      id: 15,
      attribute: 'Spooky Old House',
      title: 'The Fall of the House of Usher',
      author: 'Edgar Allan Poe',
      summary: 'Siblings have worst family reunion ever, house agrees.',
    },
    {
      id: 16,
      attribute: 'Unreliable Narrator',
      title: 'Fight Club',
      author: 'Chuck Palahniuk',
      summary: 'Man punches self, starts cult.',
    },
    {
      id: 17,
      attribute: 'Is This Art or a Typo?',
      title: 'Finnegans Wake',
      author: 'James Joyce',
      summary: 'Man dreams in word salad, readers cry.',
    },
    {
      id: 18,
      attribute: 'Hijinks',
      title: 'The Importance of Being Earnest',
      author: 'Oscar Wilde',
      summary:
        'Victorian gentlemen lie about names, cucumber sandwiches disappear.',
    },
    {
      id: 19,
      attribute: 'Comfy',
      title: 'The Wind in the Willows',
      author: 'Kenneth Grahame',
      summary:
        'Anthropomorphic animals have tea, boat rides, and existential crises.',
    },
    {
      id: 20,
      attribute: 'Slice of Life',
      title: "Bridget Jones's Diary",
      author: 'Helen Fielding',
      summary:
        'Woman counts calories, chardonnay units, and romantic misadventures.',
    },
    {
      id: 21,
      attribute: 'Fancy Words, Deep Thoughts',
      title: 'The Sound and the Fury',
      author: 'William Faulkner',
      summary:
        'Southern family falls apart, narrated by stream of consciousness.',
    },
    {
      id: 22,
      attribute: 'Survival',
      title: 'Life of Pi',
      author: 'Yann Martel',
      summary: 'Boy and tiger share lifeboat, debate reality.',
    },
    {
      id: 23,
      attribute: 'Greek Gods, Family Reunion',
      title: 'The Odyssey',
      author: 'Homer',
      summary: 'Man takes decade-long detour home, wife unimpressed.',
    },
    {
      id: 24,
      attribute: 'Hero Journey',
      title: "Harry Potter and the Philosopher's Stone",
      author: 'J.K. Rowling',
      summary: 'Orphan learns magic, defeats noseless wizard.',
    },
    {
      id: 25,
      attribute: 'Dragons and Stuff',
      title: 'The Hobbit',
      author: 'J.R.R. Tolkien',
      summary: 'Reluctant burglar steals from dragon, finds magic ring.',
    },
    {
      id: 26,
      attribute: 'The Door is a Jar',
      title: 'The Chronicles of Narnia: The Lion, the Witch and the Wardrobe',
      author: 'C.S. Lewis',
      summary: 'Kids enter closet, find Jesus lion.',
    },
    {
      id: 27,
      attribute: 'Reality Optional',
      title: 'The Metamorphosis',
      author: 'Franz Kafka',
      summary: 'Man becomes bug, family mildly inconvenienced.',
    },
    {
      id: 28,
      attribute: 'Redemption Arc',
      title: 'A Christmas Carol',
      author: 'Charles Dickens',
      summary: 'Grumpy old man haunted into generosity.',
    },
    {
      id: 29,
      attribute: 'Chaos Ensues',
      title: 'Good Omens',
      author: 'Terry Pratchett & Neil Gaiman',
      summary: 'Angel and demon lose Antichrist, paperwork nightmare ensues.',
    },
    {
      id: 30,
      attribute: 'Rags to Riches',
      title: 'The Count of Monte Cristo',
      author: 'Alexandre Dumas',
      summary: 'Sailor gets upgrade from prison to fortune, chooses revenge.',
    },
    {
      id: 31,
      attribute: 'Real Scary',
      title: 'Dracula',
      author: 'Bram Stoker',
      summary: "Realtor's trip goes badly, garlic sales skyrocket.",
    },
    {
      id: 32,
      attribute: 'Adventure',
      title: 'Around the World in Eighty Days',
      author: 'Jules Verne',
      summary: 'Man accepts bet, invents extreme tourism.',
    },
    {
      id: 33,
      attribute: 'Is This Art or a Typo?',
      title: 'Ulysses',
      author: 'James Joyce',
      summary: 'Man walks around Dublin, readers need encyclopedias.',
    },
    {
      id: 34,
      attribute: 'Fancy Words, Deep Thoughts',
      title: 'To the Lighthouse',
      author: 'Virginia Woolf',
      summary:
        'Family plans trip, ponders existence, rarely reaches lighthouse.',
    },
    {
      id: 35,
      attribute: 'Survival',
      title: 'The Martian',
      author: 'Andy Weir',
      summary: 'Botanist left on Mars, science solves everything.',
    },
    {
      id: 36,
      attribute: 'Greek Gods, Family Reunion',
      title: 'Percy Jackson & the Olympians: The Lightning Thief',
      author: 'Rick Riordan',
      summary: 'Teen discovers godly parentage, summer camp gets extreme.',
    },
    {
      id: 37,
      attribute: 'Unreliable Narrator',
      title: 'The Tell-Tale Heart',
      author: 'Edgar Allan Poe',
      summary: 'Man definitely not crazy, floor disagrees.',
    },
    {
      id: 38,
      attribute: 'Reality Optional',
      title: "The Time Traveler's Wife",
      author: 'Audrey Niffenegger',
      summary: "Man's poor time management ruins relationship.",
    },
  ])
}
