/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
export async function seed(knex) {
  // Deletes ALL existing entries
  await knex('findbooks').del()
  await knex('findbooks').insert([
    {
      id: 1,
      attribute: 'Rags to Riches',
      title: 'Great Expectations',
      author: 'Charles Dickens',
      summary: 'Orphan levels up, realizes money cannot buy class.',
    },
    {
      id: 2,
      attribute: 'Sharp Satire',
      title: 'Catch-22',
      author: 'Joseph Heller',
      summary: 'War is crazy, paperwork is crazier.',
    },
    {
      id: 3,
      attribute: 'Sharp Satire',
      title: 'Animal Farm',
      author: 'George Orwell',
      summary: 'Pigs discover communism, other animals not impressed.',
    },
    {
      id: 4,
      attribute: 'Adventure',
      title: 'Jurassic Park',
      author: 'Michael Crichton',
      summary: 'Dinosaur theme park, what could go wrong?',
    },
    {
      id: 5,
      attribute: 'Chaos Ensues',
      title: 'A Confederacy of Dunces',
      author: 'John Kennedy Toole',
      summary: 'Man-child wreaks havoc in New Orleans, calls it philosophy.',
    },
    {
      id: 6,
      attribute: 'Chaos Ensues',
      title: 'Alices Adventures in Wonderland',
      author: 'Lewis Carroll',
      summary: 'Girl follows rabbit, sanity optional.',
    },
    {
      id: 7,
      attribute: 'Real Scary',
      title: 'House of Leaves',
      author: 'Mark Z. Danielewski',
      summary: 'House bigger on inside, sanity smaller on outside.',
    },
    {
      id: 8,
      attribute: 'Real Scary',
      title: 'The Shining',
      author: 'Stephen King',
      summary: 'Family vacation goes wrong.',
    },
    {
      id: 9,
      attribute: 'Endless Family Drama',
      title: 'One Hundred Years of Solitude',
      author: 'Gabriel García Márquez',
      summary: 'Seven generations of mistakes, magic realism cannot fix it.',
    },
    {
      id: 10,
      attribute: 'Endless Family Drama',
      title: 'The God of Small Things',
      author: 'Arundhati Roy',
      summary: 'Twins learn family secrets, wish they had not.',
    },
    {
      id: 11,
      attribute: 'Chaos Ensues',
      title: "The Hitchhiker's Guide to the Galaxy",
      author: 'Douglas Adams',
      summary: 'Earth demolished, man tours universe in bathrobe.',
    },
    {
      id: 12,
      attribute: 'Rags to Riches',
      title: 'Charlie and the Chocolate Factory',
      author: 'Roald Dahl',
      summary:
        'Poor kid wins candy factory, previous owner definitely not sued.',
    },
    {
      id: 13,
      attribute: 'Real Scary',
      title: 'It',
      author: 'Stephen King',
      summary:
        'Killer clown terrorizes town, children fight back with power of friendship.',
    },
    {
      id: 14,
      attribute: 'Adventure',
      title: 'The Hobbit',
      author: 'J.R.R. Tolkien',
      summary: 'Short man takes long walk, finds jewelry.',
    },
    {
      id: 15,
      attribute: 'Spooky Old House',
      title: 'The Fall of the House of Usher',
      author: 'Edgar Allan Poe',
      summary: 'Siblings have worst family reunion ever, house agrees.',
    },
    {
      id: 16,
      attribute: 'Unreliable Narrator',
      title: 'Fight Club',
      author: 'Chuck Palahniuk',
      summary: 'Man punches self, starts cult.',
    },
    {
      id: 17,
      attribute: 'Is This Art or a Typo?',
      title: 'Finnegans Wake',
      author: 'James Joyce',
      summary: 'Man dreams in word salad, readers cry.',
    },
    {
      id: 18,
      attribute: 'Hijinks',
      title: 'The Importance of Being Earnest',
      author: 'Oscar Wilde',
      summary:
        'Victorian gentlemen lie about names, cucumber sandwiches disappear.',
    },
    {
      id: 19,
      attribute: 'Comfy',
      title: 'The Wind in the Willows',
      author: 'Kenneth Grahame',
      summary:
        'Anthropomorphic animals have tea, boat rides, and existential crises.',
    },
    {
      id: 20,
      attribute: 'Slice of Life',
      title: "Bridget Jones's Diary",
      author: 'Helen Fielding',
      summary:
        'Woman counts calories, chardonnay units, and romantic misadventures.',
    },
    {
      id: 21,
      attribute: 'Fancy Words, Deep Thoughts',
      title: 'The Sound and the Fury',
      author: 'William Faulkner',
      summary:
        'Southern family falls apart, narrated by stream of consciousness.',
    },
    {
      id: 22,
      attribute: 'Survival',
      title: 'Life of Pi',
      author: 'Yann Martel',
      summary: 'Boy and tiger share lifeboat, debate reality.',
    },
    {
      id: 23,
      attribute: 'Greek Gods, Family Reunion',
      title: 'The Odyssey',
      author: 'Homer',
      summary: 'Man takes decade-long detour home, wife unimpressed.',
    },
    {
      id: 24,
      attribute: 'Hero Journey',
      title: "Harry Potter and the Philosopher's Stone",
      author: 'J.K. Rowling',
      summary: 'Orphan learns magic, defeats noseless wizard.',
    },
    {
      id: 25,
      attribute: 'Dragons and Stuff',
      title: 'The Hobbit',
      author: 'J.R.R. Tolkien',
      summary: 'Reluctant burglar steals from dragon, finds magic ring.',
    },
    {
      id: 26,
      attribute: 'The Door is a Jar',
      title: 'The Chronicles of Narnia: The Lion, the Witch and the Wardrobe',
      author: 'C.S. Lewis',
      summary: 'Kids enter closet, find Jesus lion.',
    },
    {
      id: 27,
      attribute: 'Reality Optional',
      title: 'The Metamorphosis',
      author: 'Franz Kafka',
      summary: 'Man becomes bug, family mildly inconvenienced.',
    },
    {
      id: 28,
      attribute: 'Redemption Arc',
      title: 'A Christmas Carol',
      author: 'Charles Dickens',
      summary: 'Grumpy old man haunted into generosity.',
    },
    {
      id: 29,
      attribute: 'Chaos Ensues',
      title: 'Good Omens',
      author: 'Terry Pratchett & Neil Gaiman',
      summary: 'Angel and demon lose Antichrist, paperwork nightmare ensues.',
    },
    {
      id: 30,
      attribute: 'Rags to Riches',
      title: 'The Count of Monte Cristo',
      author: 'Alexandre Dumas',
      summary: 'Sailor gets upgrade from prison to fortune, chooses revenge.',
    },
    {
      id: 31,
      attribute: 'Real Scary',
      title: 'Dracula',
      author: 'Bram Stoker',
      summary: "Realtor's trip goes badly, garlic sales skyrocket.",
    },
    {
      id: 32,
      attribute: 'Adventure',
      title: 'Around the World in Eighty Days',
      author: 'Jules Verne',
      summary: 'Man accepts bet, invents extreme tourism.',
    },
    {
      id: 33,
      attribute: 'Is This Art or a Typo?',
      title: 'Ulysses',
      author: 'James Joyce',
      summary: 'Man walks around Dublin, readers need encyclopedias.',
    },
    {
      id: 34,
      attribute: 'Fancy Words, Deep Thoughts',
      title: 'To the Lighthouse',
      author: 'Virginia Woolf',
      summary:
        'Family plans trip, ponders existence, rarely reaches lighthouse.',
    },
    {
      id: 35,
      attribute: 'Survival',
      title: 'The Martian',
      author: 'Andy Weir',
      summary: 'Botanist left on Mars, science solves everything.',
    },
    {
      id: 36,
      attribute: 'Greek Gods, Family Reunion',
      title: 'Percy Jackson & the Olympians: The Lightning Thief',
      author: 'Rick Riordan',
      summary: 'Teen discovers godly parentage, summer camp gets extreme.',
    },
    {
      id: 37,
      attribute: 'Unreliable Narrator',
      title: 'The Tell-Tale Heart',
      author: 'Edgar Allan Poe',
      summary: 'Man definitely not crazy, floor disagrees.',
    },
    {
      id: 38,
      attribute: 'Reality Optional',
      title: "The Time Traveler's Wife",
      author: 'Audrey Niffenegger',
      summary: "Man's poor time management ruins relationship.",
    },
    {
      id: 39,
      attribute: 'Rags to Riches',
      title: 'The Great Gatsby',
      author: 'F. Scott Fitzgerald',
      summary: "Poor boy gets rich, throws parties, still can't get the girl.",
    },
    {
      id: 40,
      attribute: 'Rags to Riches',
      title: 'Memoirs of a Geisha',
      author: 'Arthur Golden',
      summary: 'Village girl becomes top-tier entertainer, drama ensues.',
    },
    {
      id: 41,
      attribute: 'Sharp Satire',
      title: 'A Modest Proposal',
      author: 'Jonathan Swift',
      summary: 'Economist suggests eating babies, readers miss the joke.',
    },
    {
      id: 42,
      attribute: 'Sharp Satire',
      title: 'Brave New World',
      author: 'Aldous Huxley',
      summary: "Dystopia where everyone's happy, it's terrifying.",
    },
    {
      id: 43,
      attribute: 'Adventure',
      title: 'Treasure Island',
      author: 'Robert Louis Stevenson',
      summary: 'Boy finds map, pirates find boy, everyone finds trouble.',
    },
    {
      id: 44,
      attribute: 'Adventure',
      title: 'Journey to the Center of the Earth',
      author: 'Jules Verne',
      summary:
        "Scientists take wrong turn at Albuquerque, end up in earth's core.",
    },
    {
      id: 45,
      attribute: 'Chaos Ensues',
      title: 'Don Quixote',
      author: 'Miguel de Cervantes',
      summary: 'Man reads too many books, attacks windmills.',
    },
    {
      id: 46,
      attribute: 'Chaos Ensues',
      title: 'Catch-22',
      author: 'Joseph Heller',
      summary: 'War is mad, staying sane is madder.',
    },
    {
      id: 47,
      attribute: 'Real Scary',
      title: 'Pet Sematary',
      author: 'Stephen King',
      summary: 'Sometimes dead is better, guy ignores advice.',
    },
    {
      id: 48,
      attribute: 'Real Scary',
      title: 'The Exorcist',
      author: 'William Peter Blatty',
      summary: 'Girl needs Advil, gets priest instead.',
    },
    {
      id: 49,
      attribute: 'Endless Family Drama',
      title: 'Wuthering Heights',
      author: 'Emily Brontë',
      summary: 'Ghosts, moors, and toxic relationships: a family tradition.',
    },
    {
      id: 50,
      attribute: 'Endless Family Drama',
      title: 'Anna Karenina',
      author: 'Leo Tolstoy',
      summary: 'Married woman finds love, loses everything else.',
    },
    {
      id: 51,
      attribute: 'Spooky Old House',
      title: 'Rebecca',
      author: 'Daphne du Maurier',
      summary: "New wife competes with dead one, house doesn't help.",
    },
    {
      id: 52,
      attribute: 'Spooky Old House',
      title: 'The Haunting of Hill House',
      author: 'Shirley Jackson',
      summary: 'House wants friends, tries too hard.',
    },
    {
      id: 53,
      attribute: 'Unreliable Narrator',
      title: 'The Yellow Wallpaper',
      author: 'Charlotter Perkins Gilman',
      summary: 'Woman redecorates room with her sanity.',
    },
    {
      id: 54,
      attribute: 'Unreliable Narrator',
      title: 'Pale Fire',
      author: 'Vladimir Nabokov',
      summary: 'Scholar annotates poem, misses point entirely.',
    },
    {
      id: 55,
      attribute: 'Is This Art or a Typo?',
      title: 'House of Leaves',
      author: 'Mark Z. Danielewski',
      summary: 'Book about a book about a film about a house. Also, footnotes.',
    },
    {
      id: 56,
      attribute: 'Is This Art or a Typo?',
      title: 'A Clockwork Orange',
      author: 'Anthony Burgess',
      summary: 'Ultraviolence and made-up slang, droogs confused.',
    },
    {
      id: 57,
      attribute: 'Hijinks',
      title: 'Three Men in a Boat',
      author: 'Jerome K. Jerome',
      summary: 'Hypochondriacs take river trip, hilarity floods.',
    },
    {
      id: 58,
      attribute: 'Hijinks',
      title: 'Jeeves and Wooster',
      author: 'P. G. Wodehouse',
      summary: 'Rich idiot saved repeatedly by smart butler.',
    },
    {
      id: 59,
      attribute: 'Comfy',
      title: "Howl's Moving Castle",
      author: 'Diana Wynne Jones',
      summary: "Girl becomes old, finds love, cleans wizard's house.",
    },
    {
      id: 60,
      attribute: 'Slice of Life',
      title: 'The Catcher in the Rye',
      author: 'J. D. Salinger',
      summary: 'Teen complains for 200 pages, becomes literary icon.',
    },
    {
      id: 61,
      attribute: 'Slice of Life',
      title: 'Normal People',
      author: 'Sally Rooney',
      summary: 'Irish millennials miscommunicate, readers swoon.',
    },
    {
      id: 62,
      attribute: 'Fancy Words, Deep Thoughts',
      title: 'Infinite Jest',
      author: 'David Foster Wallace',
      summary:
        'Tennis, addiction, and filmography collide. Footnotes mandatory.',
    },
    {
      id: 63,
      attribute: 'Fancy Words, Deep Thoughts',
      title: 'Mrs. Dalloway',
      author: 'Virginia Woolf',
      summary: 'Woman plans party, remembers entire life.',
    },
    {
      id: 64,
      attribute: 'Survival',
      title: 'Hatchet',
      author: 'Gary Paulsen',
      summary: 'Boy vs Wild: Canadian Edition.',
    },
    {
      id: 65,
      attribute: 'Survival',
      title: 'Robinson Crusoe',
      author: 'Daniel Defoe',
      summary:
        'Man builds empire on deserted island, ruins it with colonialism.',
    },
    {
      id: 66,
      attribute: 'Greek Gods, Family Reunion',
      title: 'Circe',
      author: 'Madeline Miller',
      summary: 'Witch exiled to island, turns men to pigs literally.',
    },
    {
      id: 67,
      attribute: 'Greek Gods, Family Reunion',
      title: 'The Song of Achilles',
      author: 'Madeline Miller',
      summary: 'Greek heroes in love, everyone else in trouble.',
    },
  ])
}
